name: dream_job
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  tabler_icons: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Calibril
      fonts:
        - asset: assets/fonts/calibril.ttf
      
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.TTF